// Code generated by MockGen. DO NOT EDIT.
// Source: http.go
//
// Generated by this command:
//
//	mockgen -source=http.go -destination=mocks/mock_postcontroller.go -package=mocks
//

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	reflect "reflect"

	post "github.com/anthonymartz17/blog_platform_backend.git/internal/post"
	gomock "go.uber.org/mock/gomock"
)

// MockPostController is a mock of PostController interface.
type MockPostController struct {
	ctrl     *gomock.Controller
	recorder *MockPostControllerMockRecorder
	isgomock struct{}
}

// MockPostControllerMockRecorder is the mock recorder for MockPostController.
type MockPostControllerMockRecorder struct {
	mock *MockPostController
}

// NewMockPostController creates a new mock instance.
func NewMockPostController(ctrl *gomock.Controller) *MockPostController {
	mock := &MockPostController{ctrl: ctrl}
	mock.recorder = &MockPostControllerMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockPostController) EXPECT() *MockPostControllerMockRecorder {
	return m.recorder
}

// Create mocks base method.
func (m *MockPostController) Create(ctx context.Context, arg1 *post.Post) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Create", ctx, arg1)
	ret0, _ := ret[0].(error)
	return ret0
}

// Create indicates an expected call of Create.
func (mr *MockPostControllerMockRecorder) Create(ctx, arg1 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Create", reflect.TypeOf((*MockPostController)(nil).Create), ctx, arg1)
}

// GetPosts mocks base method.
func (m *MockPostController) GetPosts(ctx context.Context) ([]post.Post, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetPosts", ctx)
	ret0, _ := ret[0].([]post.Post)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetPosts indicates an expected call of GetPosts.
func (mr *MockPostControllerMockRecorder) GetPosts(ctx any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetPosts", reflect.TypeOf((*MockPostController)(nil).GetPosts), ctx)
}
